name: flutter_attendance_clean
description: A Flutter app with Clean Architecture and SOLID principles
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.3
  geolocator: ^10.1.0
  image_picker: ^0.8.4+4
  shared_preferences: ^2.2.2
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env  